// SPDX-License-Identifier: MIT
/*
 * Copyright (C) 2018 Marco Antônio Bueno da Silva <bueno.marco@gmail.com>
 *
 * This file is part of batchpress — integration test suite.
 *
 * Tests all major features against real files generated by:
 *   tests/generate_test_images.py
 *   tests/generate_test_videos.sh
 *
 * Run:
 *   cd build && ctest --output-on-failure
 * Or directly:
 *   ./test_batchpress
 */

#include "batchpress/processor.hpp"
#include "batchpress/scanner.hpp"
#include "batchpress/video_processor.hpp"
#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <algorithm>
#include <cstdlib>

// stb_image for loading and verifying output images
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_STATIC
#define STBI_FAILURE_USERMSG
#include "../core/third_party/stb_image.h"

namespace fs = std::filesystem;
using namespace batchpress;

// ── Test data paths ───────────────────────────────────────────────────────────

static fs::path TESTDATA  = fs::path(__FILE__).parent_path() / "testdata";
static fs::path IMG_DIR   = TESTDATA / "images";
static fs::path VID_DIR   = TESTDATA / "videos";
static fs::path TMP_DIR   = fs::temp_directory_path() / "batchpress_test";

// ── Fixture ───────────────────────────────────────────────────────────────────

class BPTest : public ::testing::Test {
protected:
    void SetUp() override {
        fs::remove_all(TMP_DIR);
        fs::create_directories(TMP_DIR);
    }
    void TearDown() override { fs::remove_all(TMP_DIR); }

    bool skip_if_missing(const fs::path& dir) {
        if (!fs::exists(dir)) {
            std::cout << "  [SKIP] testdata not found: " << dir << "\n"
                      << "  Run generate_test_images.py and "
                         "generate_test_videos.sh first.\n";
            return true;
        }
        return false;
    }

    fs::path first_file(const fs::path& dir, const std::string& ext,
                        uint64_t max_bytes = UINT64_MAX) {
        for (const auto& e : fs::recursive_directory_iterator(dir)) {
            if (!e.is_regular_file()) continue;
            std::string ex = e.path().extension().string();
            std::transform(ex.begin(), ex.end(), ex.begin(), ::tolower);
            if (ex == ext && e.file_size() <= max_bytes)
                return e.path();
        }
        return {};
    }

    size_t count_files(const fs::path& dir) {
        size_t n = 0;
        for (const auto& e : fs::recursive_directory_iterator(dir))
            if (e.is_regular_file()) ++n;
        return n;
    }
};

// ══════════════════════════════════════════════════════════════════════════════
//  UNIT TESTS (no testdata required)
// ══════════════════════════════════════════════════════════════════════════════

TEST(Unit, ParseResize_Exact) {
    auto s = parse_resize("1920x1080");
    EXPECT_EQ(s.mode, ResizeSpec::Mode::Exact);
    EXPECT_EQ(s.width, 1920u);
    EXPECT_EQ(s.height, 1080u);
}

TEST(Unit, ParseResize_Percent) {
    auto s = parse_resize("50%");
    EXPECT_EQ(s.mode, ResizeSpec::Mode::Percent);
    EXPECT_FLOAT_EQ(s.pct, 0.5f);
}

TEST(Unit, ParseResize_Fit) {
    auto s = parse_resize("fit:800x600");
    EXPECT_EQ(s.mode, ResizeSpec::Mode::Fit);
    EXPECT_EQ(s.width, 800u);
    EXPECT_EQ(s.height, 600u);
}

TEST(Unit, ParseResize_Empty) {
    EXPECT_FALSE(parse_resize("").active());
}

TEST(Unit, ParseResize_BadFormat_Throws) {
    EXPECT_THROW(parse_resize("1920"), std::invalid_argument);
    EXPECT_THROW(parse_resize("-10%"), std::invalid_argument);
}

TEST(Unit, ResizeCompute_FitPreservesAspect) {
    // 4000x2000 fitted into 800x800 → 800x400
    ResizeSpec s;
    s.mode = ResizeSpec::Mode::Fit;
    s.width = 800; s.height = 800;
    auto [w, h] = s.compute(4000, 2000);
    EXPECT_EQ(w, 800u);
    EXPECT_EQ(h, 400u);
}

TEST(Unit, ResizeCompute_Percent) {
    ResizeSpec s;
    s.mode = ResizeSpec::Mode::Percent;
    s.pct  = 0.5f;
    auto [w, h] = s.compute(1000, 800);
    EXPECT_EQ(w, 500u);
    EXPECT_EQ(h, 400u);
}

TEST(Unit, ParseFormat_AllValues) {
    EXPECT_EQ(parse_format("jpg"),  ImageFormat::JPEG);
    EXPECT_EQ(parse_format("jpeg"), ImageFormat::JPEG);
    EXPECT_EQ(parse_format("PNG"),  ImageFormat::PNG);
    EXPECT_EQ(parse_format("webp"), ImageFormat::WebP);
    EXPECT_EQ(parse_format("bmp"),  ImageFormat::BMP);
    EXPECT_EQ(parse_format("same"), ImageFormat::Same);
    EXPECT_EQ(parse_format(""),     ImageFormat::Same);
    EXPECT_THROW(parse_format("gif"), std::invalid_argument);
}

TEST(Unit, DiskFreeBytes_NonZero) {
    EXPECT_GT(disk_free_bytes(fs::current_path()), 0u);
}

TEST(Unit, BatchReport_Calculations) {
    BatchReport r;
    r.input_bytes_total  = 1000;
    r.output_bytes_total =  400;
    r.succeeded = 10;
    r.elapsed_sec = 2.0;
    EXPECT_DOUBLE_EQ(r.savings_pct(), 60.0);
    EXPECT_EQ(r.bytes_saved(), 600);
    EXPECT_DOUBLE_EQ(r.throughput(), 5.0);
}

TEST(Unit, CodecCaps_BestVideo) {
    CodecCaps caps = probe_codec_caps();
    VideoCodec best = caps.best_video();
    EXPECT_TRUE(best == VideoCodec::H265 ||
                best == VideoCodec::H264 ||
                best == VideoCodec::VP9)
        << "No usable video encoder found";

    std::cout << "  System codecs:"
              << " H.265=" << caps.has_h265
              << " H.264=" << caps.has_h264
              << " VP9="   << caps.has_vp9
              << " AAC="   << caps.has_aac
              << " Opus="  << caps.has_opus << "\n";
}

// ══════════════════════════════════════════════════════════════════════════════
//  IMAGE INTEGRATION TESTS
// ══════════════════════════════════════════════════════════════════════════════

TEST_F(BPTest, Images_CollectFindsAllFormats) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    Config cfg;
    cfg.input_dir = IMG_DIR;
    cfg.recursive = true;
    auto imgs = collect_images(cfg);

    ASSERT_GT(imgs.size(), 0u);

    bool jpg=false, png=false, bmp=false;
    for (const auto& p : imgs) {
        std::string ext = p.extension().string();
        std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
        if (ext==".jpg"||ext==".jpeg") jpg=true;
        if (ext==".png") png=true;
        if (ext==".bmp") bmp=true;
    }
    EXPECT_TRUE(jpg) << "No JPG found";
    EXPECT_TRUE(png) << "No PNG found";
    EXPECT_TRUE(bmp) << "No BMP found";

    std::cout << "  Found " << imgs.size() << " images (jpg/png/bmp ✓)\n";
}

TEST_F(BPTest, Images_RecursiveVsFlat) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    Config cr; cr.input_dir = IMG_DIR; cr.recursive = true;
    Config cf; cf.input_dir = IMG_DIR; cf.recursive = false;
    EXPECT_GT(collect_images(cr).size(), collect_images(cf).size());
}

TEST_F(BPTest, Images_ConvertJPGtoWebP) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    fs::path src = first_file(IMG_DIR, ".jpg");
    if (src.empty()) GTEST_SKIP() << "No JPG in testdata";

    Config cfg;
    cfg.input_dir  = IMG_DIR;
    cfg.output_dir = TMP_DIR;
    cfg.format     = ImageFormat::WebP;
    cfg.quality    = 85;

    TaskResult r = process_image(src, cfg);
    EXPECT_TRUE(r.success)   << r.error_msg;
    EXPECT_FALSE(r.skipped);
    EXPECT_TRUE(fs::exists(r.output_path));
    EXPECT_GT(r.output_bytes, 0u);

    std::cout << "  JPG→WebP: " << src.filename()
              << "  " << r.input_bytes/1024 << " KB"
              << " → " << r.output_bytes/1024 << " KB\n";
}

TEST_F(BPTest, Images_ConvertPNGtoJPG_Resize) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    fs::path src = first_file(IMG_DIR, ".png");
    if (src.empty()) GTEST_SKIP() << "No PNG in testdata";

    Config cfg;
    cfg.input_dir  = IMG_DIR;
    cfg.output_dir = TMP_DIR;
    cfg.format     = ImageFormat::JPEG;
    cfg.quality    = 80;
    cfg.resize     = parse_resize("50%");

    TaskResult r = process_image(src, cfg);
    EXPECT_TRUE(r.success) << r.error_msg;
    EXPECT_TRUE(fs::exists(r.output_path));
    std::cout << "  PNG→JPG 50%: " << src.filename()
              << "  " << r.input_bytes/1024 << " KB"
              << " → " << r.output_bytes/1024 << " KB\n";
}

TEST_F(BPTest, Images_DryRun_SourceUnchanged) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    fs::path src = first_file(IMG_DIR, ".jpg");
    if (src.empty()) GTEST_SKIP();

    uint64_t orig_size = fs::file_size(src);

    Config cfg;
    cfg.input_dir = IMG_DIR;
    cfg.output_dir= IMG_DIR;
    cfg.dry_run   = true;
    cfg.format    = ImageFormat::WebP;
    cfg.quality   = 40;
    cfg.resize    = parse_resize("10%");

    TaskResult r = process_image(src, cfg);
    EXPECT_TRUE(r.success);
    EXPECT_TRUE(r.dry_run);
    EXPECT_GT(r.output_bytes, 0u)   << "Dry-run must return size estimate";
    EXPECT_EQ(fs::file_size(src), orig_size) << "Dry-run modified source file!";

    // No output written
    fs::path out = r.output_path;
    if (out != src) { EXPECT_FALSE(fs::exists(out)) << "Dry-run created output!"; }

    std::cout << "  Dry-run: " << orig_size/1024 << " KB → estimated "
              << r.output_bytes/1024 << " KB\n";
}

TEST_F(BPTest, Images_BatchCopy_AllSucceed) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    Config cfg;
    cfg.input_dir  = IMG_DIR;
    cfg.output_dir = TMP_DIR / "batch";
    cfg.format     = ImageFormat::WebP;
    cfg.quality    = 50;       // Low quality to ensure significant compression
    cfg.resize     = parse_resize("fit:1280x720");
    cfg.recursive  = true;

    uint32_t cb = 0;
    cfg.on_progress = [&](const TaskResult&, uint32_t, uint32_t){ ++cb; };

    BatchReport r = run_batch(cfg);

    EXPECT_EQ(r.failed, 0u)      << r.failed << " images failed";
    EXPECT_GT(r.succeeded, 0u);
    EXPECT_EQ(cb, r.total)       << "Progress callback not called for all tasks";
    // Note: WebP at quality 50 should be smaller than mixed format originals
    // If this fails, it means some originals were already highly compressed

    std::cout << "  Batch: " << r.total << " images"
              << "  " << r.input_bytes_total/1024 << " KB"
              << " → " << r.output_bytes_total/1024 << " KB"
              << "  (" << std::fixed << std::setprecision(1)
              << r.savings_pct() << "% saved)\n";
}

TEST_F(BPTest, Images_BatchDryRun_NoFilesCreated) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    size_t before = count_files(IMG_DIR);

    Config cfg;
    cfg.input_dir  = IMG_DIR;
    cfg.output_dir = IMG_DIR;
    cfg.dry_run    = true;
    cfg.format     = ImageFormat::WebP;
    cfg.recursive  = true;

    BatchReport r = run_batch(cfg);
    EXPECT_TRUE(r.dry_run);
    EXPECT_GT(r.total, 0u);

    EXPECT_EQ(count_files(IMG_DIR), before) << "Dry-run created files!";

    std::cout << "  Dry-run batch: " << r.total
              << " images  projected " << std::fixed << std::setprecision(1)
              << r.savings_pct() << "% saving\n";
}

TEST_F(BPTest, Images_SkipExisting) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    Config cfg;
    cfg.input_dir    = IMG_DIR;
    cfg.output_dir   = TMP_DIR / "skip";
    cfg.format       = ImageFormat::PNG;
    cfg.recursive    = true;
    cfg.skip_existing= true;

    BatchReport r1 = run_batch(cfg);
    ASSERT_EQ(r1.failed, 0u);

    BatchReport r2 = run_batch(cfg);
    EXPECT_EQ(r2.skipped, r1.succeeded)
        << "Second run should skip all already-processed files";

    std::cout << "  First: " << r1.succeeded << " processed  "
              << "Second: " << r2.skipped   << " skipped ✓\n";
}

TEST_F(BPTest, Images_InPlace_ReducesSize) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    // Clean TMP_DIR first
    fs::remove_all(TMP_DIR);
    fs::create_directories(TMP_DIR);

    // Copy a large JPG to tmp and process in-place (changes extension to WebP)
    fs::path src = first_file(IMG_DIR, ".jpg");
    if (src.empty()) GTEST_SKIP();

    fs::path copy = TMP_DIR / "inplace.jpg";
    fs::copy_file(src, copy);
    uint64_t orig = fs::file_size(copy);

    Config cfg;
    cfg.input_dir  = TMP_DIR;
    cfg.output_dir = "";       // in-place
    cfg.format     = ImageFormat::WebP;
    cfg.quality    = 70;
    cfg.recursive  = false;

    BatchReport r = run_batch(cfg);
    EXPECT_EQ(r.failed, 0u);

    // After in-place processing with format change, extension changes
    fs::path out = copy; 
    out.replace_extension(".webp");
    ASSERT_TRUE(fs::exists(out)) << "In-place output not found: " << out;
    EXPECT_GT(fs::file_size(out), 0u);

    // Original JPG should no longer exist (replaced by WebP)
    EXPECT_FALSE(fs::exists(copy)) << "Original should be replaced";

    std::cout << "  In-place: " << orig/1024 << " KB (JPG)"
              << " → " << fs::file_size(out)/1024 << " KB (WebP)\n";
}

TEST_F(BPTest, Images_InPlace_NoExtraFiles) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    // Test that in-place processing does not leave extra files behind
    fs::path src = first_file(IMG_DIR, ".jpg");
    if (src.empty()) GTEST_SKIP();

    fs::path copy = TMP_DIR / "inplace_test.jpg";
    fs::copy_file(src, copy);
    
    // Count files before processing
    size_t files_before = count_files(TMP_DIR);
    
    Config cfg;
    cfg.input_dir  = TMP_DIR;
    cfg.output_dir = "";       // in-place
    cfg.format     = ImageFormat::WebP;
    cfg.quality    = 70;
    cfg.recursive  = false;

    BatchReport r = run_batch(cfg);
    EXPECT_EQ(r.failed, 0u);
    
    // Count files after processing
    size_t files_after = count_files(TMP_DIR);
    
    // Should have same number of files (original replaced, not added)
    // Note: extension changes from .jpg to .webp, so we check no temp files remain
    EXPECT_EQ(files_after, files_before) 
        << "In-place processing should not create extra files";
    
    // Verify no temporary files left behind
    for (const auto& e : fs::recursive_directory_iterator(TMP_DIR)) {
        std::string fname = e.path().filename().string();
        EXPECT_EQ(fname.find(".batchpress.tmp"), std::string::npos) 
            << "Temporary file found after completion: " << e.path();
    }
    
    std::cout << "  In-place: " << files_before << " files before → " 
              << files_after << " files after (no extras ✓)\n";
}

TEST_F(BPTest, Images_InPlace_DirectMode_HashRecorded) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    // Test that Direct mode (forced via env var) records SHA-256 hash
    fs::path src = first_file(IMG_DIR, ".jpg", 500*1024); // Small file ≤500KB
    if (src.empty()) GTEST_SKIP();

    fs::path copy = TMP_DIR / "direct_test.jpg";
    fs::copy_file(src, copy);
    uint64_t orig_size = fs::file_size(copy);

    // Force Direct mode via environment variable
    setenv("BATCHPRESS_FORCE_DIRECT", "1", 1);

    Config cfg;
    cfg.input_dir  = TMP_DIR;
    cfg.output_dir = "";       // in-place
    cfg.format     = ImageFormat::WebP;
    cfg.quality    = 85;
    cfg.recursive  = false;

    TaskResult result = process_image(copy, cfg);

    // Clean up environment variable
    unsetenv("BATCHPRESS_FORCE_DIRECT");

    EXPECT_TRUE(result.success) << result.error_msg;
    EXPECT_GT(result.output_bytes, 0u);

    // Direct mode MUST record SHA-256 for recovery
    EXPECT_EQ(result.write_mode, WriteMode::Direct)
        << "Direct mode should be forced by env var";
    EXPECT_FALSE(result.original_sha256.empty())
        << "Direct mode must record SHA-256 for recovery";
    EXPECT_EQ(result.original_sha256.length(), 64u)
        << "SHA-256 hash should be 64 hex characters";

    std::cout << "  Direct mode used: hash=" 
              << result.original_sha256.substr(0, 16) << "...\n";
    std::cout << "  Direct/Safe test: " << orig_size/1024 << " KB → " 
              << result.output_bytes/1024 << " KB  mode=Direct ✓\n";
}

TEST_F(BPTest, Images_InPlace_VerifyOutputIntegrity) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    // Verify that in-place processed file can be loaded back as valid image
    fs::path src = first_file(IMG_DIR, ".png");
    if (src.empty()) GTEST_SKIP();

    fs::path copy = TMP_DIR / "integrity_test.png";
    fs::copy_file(src, copy);

    Config cfg;
    cfg.input_dir  = TMP_DIR;
    cfg.output_dir = "";       // in-place
    cfg.format     = ImageFormat::JPEG;
    cfg.quality    = 80;
    cfg.recursive  = false;

    TaskResult result = process_image(copy, cfg);
    EXPECT_TRUE(result.success) << result.error_msg;
    
    fs::path out = copy;
    out.replace_extension(".jpg");
    ASSERT_TRUE(fs::exists(out)) << "Output file not found";
    
    // Try to load the output file to verify it's a valid image
    int w=0, h=0, ch=0;
    unsigned char* pixels = stbi_load(out.string().c_str(), &w, &h, &ch, 0);
    EXPECT_NE(pixels, nullptr) 
        << "Output file is not a valid image: " << stbi_failure_reason();
    EXPECT_GT(w, 0);
    EXPECT_GT(h, 0);
    EXPECT_GT(ch, 0);
    
    if (pixels) stbi_image_free(pixels);
    
    std::cout << "  Integrity check: output is valid " 
              << w << "x" << h << "x" << ch << " image ✓\n";
}

// ══════════════════════════════════════════════════════════════════════════════
//  SCAN TESTS
// ══════════════════════════════════════════════════════════════════════════════

TEST_F(BPTest, Scan_ProducesReport) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    ScanConfig cfg;
    cfg.root_dir        = IMG_DIR;
    cfg.recursive       = true;
    cfg.samples_per_dir = 3;

    uint32_t cb = 0;
    cfg.on_progress = [&](const std::string&, uint32_t, uint32_t){ ++cb; };

    ScanReport r = run_scan(cfg);
    EXPECT_GT(r.total_images, 0u);
    EXPECT_GT(r.total_bytes,  0u);
    EXPECT_GT(r.directories.size(), 0u);
    EXPECT_GT(r.savings_pct(), 0.0);
    EXPECT_GT(cb, 0u);

    std::string cmd = r.suggested_command();
    EXPECT_FALSE(cmd.empty());
    EXPECT_NE(cmd.find("batchpress"), std::string::npos);

    std::cout << "  Scan: " << r.total_images << " images"
              << "  " << r.directories.size() << " dirs"
              << "  projected " << std::fixed << std::setprecision(1)
              << r.savings_pct() << "% saving\n";
    std::cout << "  Suggested: " << cmd << "\n";
}

TEST_F(BPTest, Scan_CandidatesSortedBySavings) {
    if (skip_if_missing(IMG_DIR)) GTEST_SKIP();

    ScanConfig cfg;
    cfg.root_dir        = IMG_DIR;
    cfg.recursive       = true;
    cfg.samples_per_dir = 3;

    ScanReport r = run_scan(cfg);
    for (const auto& dir : r.directories) {
        for (size_t i = 1; i < dir.candidates.size(); ++i) {
            EXPECT_LE(dir.candidates[i].savings_pct,
                      dir.candidates[i-1].savings_pct + 0.01)
                << "Candidates not sorted descending in " << dir.directory;
        }
    }
}

// ══════════════════════════════════════════════════════════════════════════════
//  VIDEO TESTS
// ══════════════════════════════════════════════════════════════════════════════

TEST_F(BPTest, Video_ReadMeta) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    fs::path src = first_file(VID_DIR, ".mp4");
    if (src.empty()) src = first_file(VID_DIR, ".mov");
    if (src.empty()) GTEST_SKIP() << "No MP4/MOV in testdata";

    VideoMeta m = read_video_meta(src);
    EXPECT_TRUE(m.readable)    << "Could not read: " << src;
    EXPECT_GT(m.width,        0);
    EXPECT_GT(m.height,       0);
    EXPECT_GT(m.duration_sec, 0);
    EXPECT_GT(m.fps,          0);
    EXPECT_GT(m.file_bytes,   0);

    std::cout << "  Meta: " << src.filename()
              << "  " << m.width << "x" << m.height
              << "  " << std::fixed << std::setprecision(1) << m.duration_sec << "s"
              << "  " << m.video_codec_name
              << "  " << m.file_bytes/1024 << " KB\n";
}

TEST_F(BPTest, Video_DryRun_SourceUnchanged) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    fs::path src = first_file(VID_DIR, ".mp4", 10*1024*1024); // ≤10MB
    if (src.empty()) GTEST_SKIP() << "No small MP4 in testdata";

    uint64_t orig = fs::file_size(src);

    VideoConfig cfg;
    cfg.input_dir  = VID_DIR;
    cfg.output_dir = TMP_DIR;
    cfg.dry_run    = true;

    VideoResult r = process_video(src, cfg);
    EXPECT_TRUE(r.success)  << r.error_msg;
    EXPECT_TRUE(r.dry_run);
    EXPECT_GT(r.output_bytes, 0u) << "Dry-run must return size estimate";
    EXPECT_EQ(fs::file_size(src), orig) << "Dry-run modified source!";
    EXPECT_FALSE(fs::exists(r.output_path)) << "Dry-run created output file!";

    std::cout << "  Video dry-run: " << src.filename()
              << "  " << orig/1024 << " KB → estimated "
              << r.output_bytes/1024 << " KB\n";
}

TEST_F(BPTest, Video_CopyMode_ProducesOutput) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    // Use smallest video for speed
    fs::path src = first_file(VID_DIR, ".mp4", 3*1024*1024);
    if (src.empty()) GTEST_SKIP() << "No small MP4 (≤3MB) in testdata";

    VideoConfig cfg;
    cfg.input_dir  = VID_DIR;
    cfg.output_dir = TMP_DIR / "vid_out";
    cfg.video_codec= VideoCodec::Auto;
    cfg.resolution = ResolutionCap::Cap1080p;
    cfg.dry_run    = false;

    uint32_t frame_cb = 0;
    cfg.on_progress = [&](const fs::path&, uint64_t, uint64_t,
                          uint32_t, uint32_t){ ++frame_cb; };

    VideoResult r = process_video(src, cfg);
    EXPECT_TRUE(r.success)          << r.error_msg;
    EXPECT_TRUE(fs::exists(r.output_path));
    EXPECT_GT(r.output_bytes, 0u);
    EXPECT_GT(frame_cb, 0u)        << "Frame callback never called";

    std::cout << "  Video transcode: " << src.filename()
              << "  " << r.input_bytes/1024 << " KB"
              << " → " << r.output_bytes/1024 << " KB"
              << "  codec=" << static_cast<int>(r.codec_used)
              << "  crf=" << r.crf_used << "\n";
}

TEST_F(BPTest, Video_ScanReport) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    VideoScanConfig cfg;
    cfg.root_dir  = VID_DIR;
    cfg.recursive = true;

    uint32_t cb = 0;
    cfg.on_progress = [&](const std::string&, uint32_t, uint32_t){ ++cb; };

    VideoScanReport r = run_video_scan(cfg);
    if (r.total_videos == 0) GTEST_SKIP() << "No videos in testdata";

    EXPECT_GT(r.total_bytes, 0u);
    EXPECT_GT(r.directories.size(), 0u);
    EXPECT_GT(r.savings_pct(), 0.0);
    EXPECT_GT(cb, 0u);
    EXPECT_FALSE(r.suggested_command().empty());

    std::cout << "  Video scan: " << r.total_videos << " videos"
              << "  " << r.total_bytes/(1024*1024) << " MB"
              << "  projected " << std::fixed << std::setprecision(1)
              << r.savings_pct() << "% saving\n";
    std::cout << "  Suggested: " << r.suggested_command() << "\n";
}

TEST_F(BPTest, Video_BatchDryRun) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    VideoConfig cfg;
    cfg.input_dir  = VID_DIR;
    cfg.output_dir = TMP_DIR;
    cfg.dry_run    = true;
    cfg.recursive  = true;

    VideoBatchReport r = run_video_batch(cfg);
    if (r.total == 0) GTEST_SKIP() << "No videos in testdata";

    EXPECT_TRUE(r.dry_run);
    EXPECT_EQ(r.failed, 0u);
    EXPECT_GT(r.succeeded, 0u);

    size_t files_in_tmp = count_files(TMP_DIR);
    EXPECT_EQ(files_in_tmp, 0u) << "Dry-run created files in output!";

    std::cout << "  Video batch dry-run: " << r.total << " files"
              << "  projected " << std::fixed << std::setprecision(1)
              << r.savings_pct() << "% saving\n";
}

TEST_F(BPTest, Video_InPlace_ReducesSize) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    // Clean TMP_DIR first
    fs::remove_all(TMP_DIR);
    fs::create_directories(TMP_DIR);

    // Copy a small video to tmp and process in-place with H.265
    fs::path src = first_file(VID_DIR, ".mp4", 3*1024*1024); // ≤3MB
    if (src.empty()) GTEST_SKIP();

    fs::path copy = TMP_DIR / "inplace.mp4";
    fs::copy_file(src, copy);
    uint64_t orig = fs::file_size(copy);

    VideoConfig cfg;
    cfg.input_dir   = TMP_DIR;
    cfg.output_dir  = "";        // in-place
    cfg.video_codec = VideoCodec::H265;
    cfg.crf         = 28;
    cfg.recursive   = false;

    VideoResult r = process_video(copy, cfg);
    EXPECT_TRUE(r.success) << r.error_msg;

    // Output should be at same path (in-place)
    ASSERT_TRUE(fs::exists(r.output_path)) << "In-place output not found";
    EXPECT_GT(r.output_bytes, 0u);

    std::cout << "  Video In-place: " << orig/1024 << " KB → " 
              << r.output_bytes/1024 << " KB  codec=" 
              << static_cast<int>(r.codec_used) << "\n";
}

TEST_F(BPTest, Video_InPlace_NoExtraFiles) {
    if (skip_if_missing(VID_DIR)) GTEST_SKIP();

    // Clean TMP_DIR first
    fs::remove_all(TMP_DIR);
    fs::create_directories(TMP_DIR);

    // Copy a small video to tmp
    fs::path src = first_file(VID_DIR, ".mp4", 3*1024*1024);
    if (src.empty()) GTEST_SKIP();

    fs::path copy = TMP_DIR / "inplace_test.mp4";
    fs::copy_file(src, copy);

    // Count files before processing
    size_t files_before = count_files(TMP_DIR);

    VideoConfig cfg;
    cfg.input_dir   = TMP_DIR;
    cfg.output_dir  = "";        // in-place
    cfg.video_codec = VideoCodec::H265;
    cfg.recursive   = false;

    VideoResult r = process_video(copy, cfg);
    EXPECT_TRUE(r.success) << r.error_msg;

    // Count files after processing
    size_t files_after = count_files(TMP_DIR);

    // Should have same number of files (1 file processed in-place)
    EXPECT_EQ(files_after, files_before)
        << "In-place processing should not create extra files";

    // Verify no temporary files left behind
    for (const auto& e : fs::recursive_directory_iterator(TMP_DIR)) {
        std::string fname = e.path().filename().string();
        EXPECT_EQ(fname.find(".tmp"), std::string::npos)
            << "Temporary file found after completion: " << e.path();
    }

    std::cout << "  Video In-place: " << files_before << " files before → "
              << files_after << " files after (no extras ✓)\n";
}

// ══════════════════════════════════════════════════════════════════════════════
//  MAIN
// ══════════════════════════════════════════════════════════════════════════════

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);

    std::cout
        << "\n╔══════════════════════════════════════════════════╗\n"
        << "║       batchpress — Integration Test Suite        ║\n"
        << "╚══════════════════════════════════════════════════╝\n\n"
        << "  images dir : " << IMG_DIR << "\n"
        << "  videos dir : " << VID_DIR << "\n\n";

    if (!fs::exists(IMG_DIR))
        std::cout << "  ⚠  Image testdata missing.\n"
                  << "     Run: python3 tests/generate_test_images.py\n\n";
    if (!fs::exists(VID_DIR))
        std::cout << "  ⚠  Video testdata missing.\n"
                  << "     Run: bash tests/generate_test_videos.sh\n\n";

    return RUN_ALL_TESTS();
}
